# file: nginx/handlers/main.yml

- name: restart nginx
  service: name=nginx state=restarted
  become: yes
  # we will manage nginx from supervisor, so don't start nginx using systemctl / service or it will conflict
  when: not nginx_first_start.changed and not nginx_daemon_disable

- name: reload nginx
  service: name=nginx state=reloaded
  become: yes
  # we will manage nginx from supervisor, so don't start nginx using systemctl / service or it will conflict
  when: not nginx_daemon_disable
